.github/dependabot.yaml, .github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/renew.yaml, composer.json, composer.lock
💁‍♂️ For reference, see https://github.com/theseer/phpunit/pull/1.
=> Enhancement: Require phpunit/phpunit:dev-event from @theseer's fork

.github/workflows/integrate.yaml, Makefile, test/Example/ExampleTest.php, test/Example/phpunit.xml, test/Fixture/Sleeper.php
=> Enhancement: Add example tests

CHANGELOG.md, src/SlowTestCollector.php, test/Unit/SlowTestCollectorTest.php
=> Enhancement: Implement SlowTestCollector

src/SlowTestCollector.php, test/Unit/SlowTestCollectorTest.php
=> Enhancement: Collect SlowTests indirectly

src/SlowTestCollector.php, test/Unit/SlowTestCollectorTest.php
=> Fix: Rename methods

test/Unit/SlowTestCollectorTest.php
=> Fix: Clarify tests

CHANGELOG.md, src/Subscriber/TestPassedSubscriber.php, test/Unit/Subscriber/TestPassedSubscriberTest.php
=> Enhancement: Implement TestPassedSubscriber

test/Unit/SlowTestCollectorTest.php
=> Enhancement: Use numeric literal separator

.github/settings.yml, .php_cs, CHANGELOG.md, README.md, composer.json, composer.lock, src/SlowTest.php, src/SlowTestCollector.php, src/Subscriber/TestPassedSubscriber.php, src/Subscriber/TestPreparedSubscriber.php, test/AutoReview/SrcCodeTest.php, test/Example/ExampleTest.php, test/Fixture/Sleeper.php, test/Unit/SlowTestCollectorTest.php, test/Unit/SlowTestTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php, test/Unit/Subscriber/TestPreparedSubscriberTest.php
=> Fix: Rename repository

CHANGELOG.md, src/Comparator/DurationComparator.php, test/Unit/Comparator/DurationComparatorTest.php
=> Enhancement: Implement DurationComparator

CHANGELOG.md, src/Reporter/Reporter.php, test/Unit/Reporter/ReporterTest.php
=> Enhancement: Rename SlowTestReporter to Reporter\Reporter

CHANGELOG.md, src/SlowTestCollector.php, src/TimeKeeper.php, test/Unit/SlowTestCollectorTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php, test/Unit/Subscriber/TestPreparedSubscriberTest.php, test/Unit/TimeKeeperTest.php
=> Enhancement: Extract TimeKeeper

test/Example/SleeperTest.php
=> Fix: Rename test

.github/settings.yml, README.md, composer.json
=> Fix: Description

.github/workflows/integrate.yaml, CHANGELOG.md, Makefile, src/Subscriber/TestSuiteFinishedSubscriber.php, test/Double/Reporter/CountingReporter.php, test/Double/Reporter/NullReporter.php, test/Example/bootstrap.php, test/Example/phpunit.xml, test/Unit/Subscriber/TestSuiteFinishedSubscriberTest.php
=> Enhancement: Implement TestSuiteFinishedSubscriber

src/Reporter/DefaultReporter.php, test/Unit/Reporter/DefaultReporterTest.php
=> Fix: Remove colon

test/Unit/Collector/DefaultCollectorTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php, test/Unit/TimeKeeperTest.php
=> Fix: Clone tests

.github/workflows/integrate.yaml, infection.json
=> Enhancement: Synchronize with ergebnis/php-library-template

.github/workflows/integrate.yaml, .github/workflows/triage.yaml
=> Fix: Adjust usage of octokit

.github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/renew.yaml, composer.json, composer.lock
=> Fix: Require PHP 8.0

test/Example/SleeperTest.php, test/Unit/Collector/DefaultCollectorTest.php, test/Unit/Comparator/DurationComparatorTest.php, test/Unit/Console/ColorTest.php, test/Unit/Exception/InvalidMaximumCountTest.php, test/Unit/Exception/InvalidMaximumDurationTest.php, test/Unit/Formatter/ToMillisecondsDurationFormatterTest.php, test/Unit/MaximumDurationTest.php, test/Unit/Reporter/DefaultReporterTest.php, test/Unit/SlowTestTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php, test/Unit/Subscriber/TestPreparedSubscriberTest.php, test/Unit/Subscriber/TestSuiteFinishedSubscriberTest.php, test/Unit/TimeKeeperTest.php, test/Util/Helper.php
=> Enhancement: Pull in `Helper` from `ergebnis/test-util`

composer.json, composer.lock, psalm-baseline.xml
=> Enhancement: Require `fakerphp/faker`

.github/workflows/integrate.yaml, .github/workflows/renew.yaml, .php-cs-fixer.php, Makefile, composer.json, composer.lock, src/Exception/InvalidMaximumCount.php, src/Exception/InvalidMaximumDuration.php, src/Formatter/ToMillisecondsDurationFormatter.php, src/MaximumDuration.php, src/Reporter/DefaultReporter.php, src/SlowTest.php, src/Subscriber/TestPassedSubscriber.php, src/Subscriber/TestPreparedSubscriber.php, src/Subscriber/TestSuiteFinishedSubscriber.php, src/TimeKeeper.php, test/Example/Sleeper.php, test/Example/bootstrap.php, test/Unit/Collector/DefaultCollectorTest.php, test/Unit/Comparator/DurationComparatorTest.php, test/Unit/Exception/InvalidMaximumCountTest.php, test/Unit/Exception/InvalidMaximumDurationTest.php, test/Unit/Formatter/ToMillisecondsDurationFormatterTest.php, test/Unit/MaximumDurationTest.php, test/Unit/Reporter/DefaultReporterTest.php, test/Unit/SlowTestTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php, test/Unit/Subscriber/TestPreparedSubscriberTest.php, test/Unit/Subscriber/TestSuiteFinishedSubscriberTest.php, test/Unit/TimeKeeperTest.php
=> Enhancement: Update `ergebnis/php-cs-fixer-config`

test/Double/Collector/AppendingCollector.php, test/Unit/Collector/DefaultCollectorTest.php, test/Unit/Comparator/DurationComparatorTest.php, test/Unit/Console/ColorTest.php, test/Unit/Exception/InvalidMaximumCountTest.php, test/Unit/Exception/InvalidMaximumDurationTest.php, test/Unit/Formatter/ToMillisecondsDurationFormatterTest.php, test/Unit/Reporter/DefaultReporterTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php, test/Unit/Subscriber/TestPreparedSubscriberTest.php, test/Unit/Subscriber/TestSuiteFinishedSubscriberTest.php, test/Unit/TimeKeeperTest.php
=> Fix: Avoid unnecessary imports

src/MaximumCount.php, src/MaximumDuration.php, src/SlowTest.php
=> Fix: Declare objects as immutable

infection.json, psalm-baseline.xml, src/Formatter/ToMillisecondsDurationFormatter.php
=> Fix: Inline method

.github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/renew.yaml, composer.json, composer.lock
=> Fix: Require PHP 8.1

CHANGELOG.md, README.md, src/Extension.php, test/EndToEnd/MaximumCount/Default/phpunit.xml, test/EndToEnd/MaximumCount/Default/test.phpt, test/EndToEnd/MaximumCount/Five/phpunit.xml, test/EndToEnd/MaximumCount/Five/test.phpt
=> Enhancement: Allow configuring the maximum count via `maximum-count` parameter

CHANGELOG.md, README.md, src/Extension.php, test/EndToEnd/MaximumCount/Default/test.phpt, test/EndToEnd/MaximumCount/Five/test.phpt, test/EndToEnd/MaximumDuration/Default/test.phpt, test/EndToEnd/MaximumDuration/Fifty/test.phpt
=> Fix: Adjust defaults

CHANGELOG.md, README.md, psalm-baseline.xml, src/Subscriber/TestPassedSubscriber.php, test/EndToEnd/MaximumDuration/Fifty/SleeperTest.php, test/EndToEnd/MaximumDuration/Fifty/test.phpt
=> Enhancement: Allow configuring the maximum duration via `@maximumDuration` annotation

.github/CODEOWNERS, .github/CONTRIBUTING.md, .github/SECURITY.md, .github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/renew.yaml, .gitignore, .php-cs-fixer.php, .yamllint.yaml, Makefile, composer-require-checker.json, psalm-baseline.xml, rector.php, test/EndToEnd/Default/SleeperTest.php, test/EndToEnd/MaximumCount/Five/SleeperTest.php, test/EndToEnd/MaximumDuration/Fifty/SleeperTest.php, test/EndToEnd/NoOutput/SleeperTest.php, test/Fixture/Sleeper.php, test/Unit/Comparator/DurationComparatorTest.php, test/Unit/Console/ColorTest.php, test/Unit/Exception/InvalidMaximumCountTest.php, test/Unit/Exception/InvalidMaximumDurationTest.php, test/Unit/Formatter/DefaultDurationFormatterTest.php, test/Unit/MaximumCountTest.php, test/Unit/MaximumDurationTest.php
=> Enhancement: Synchronize with `ergebnis/php-package-template`

CHANGELOG.md, composer-require-checker.json, composer.json, composer.lock
=> Fix: Suggest and require `phpunit/phpunit:^10.0.1` as development dependency

CHANGELOG.md, manifest.xml
=> Fix: Adjust version in `manifest.xml`

CHANGELOG.md, composer.json, composer.lock, manifest.xml
=> Enhancement: Require `phpunit/phpunit:^10.4.2`

.github/workflows/integrate.yaml, Makefile, test/EndToEnd/phpunit.xml, test/Unit/phpunit.xml
=> Enhancement: Collect code coverage from running unit tests only

src/Extension.php
=> Fix: Remove unused field

.github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/release.yaml, .github/workflows/renew.yaml, .phive/phars.xml, .php-cs-fixer.php, composer-require-checker.json, composer.json, composer.lock, psalm-baseline.xml, rector.php, src/Attribute/MaximumDuration.php, src/Count.php, src/Duration.php, src/Extension.php, src/Reporter/DefaultReporter.php, src/SlowTest.php, src/Subscriber/TestPassedSubscriber.php, src/Subscriber/TestPreparedSubscriber.php, src/Subscriber/TestRunnerExecutionFinishedSubscriber.php, src/TestIdentifier.php, src/Time.php, test/Fixture/Sleeper.php
Partially replaces #371.
Related to #369.
=> Enhancement: Add support for PHP 8.0

.github/workflows/integrate.yaml, .github/workflows/release.yaml
=> Fix: Order

test/EndToEnd/Version8/CustomConfiguration/phpunit.xml, test/EndToEnd/Version8/DefaultConfiguration/phpunit.xml, test/EndToEnd/Version8/phpunit.xml, test/Unit/phpunit.xml
=> Fix: Schema

README.md
=> Enhancement: Add documentation about understanding measured test durations

test/Phar/SleeperTest.php, test/Unit/Comparator/DurationComparatorTest.php, test/Unit/Exception/InvalidTestIdentifierTest.php, test/Unit/Formatter/DefaultDurationFormatterTest.php
=> Fix: Remove unused imports

psalm-baseline.xml, src/Extension.php, src/Subscriber/Test/PassedSubscriber.php, src/Subscriber/Test/PreparedSubscriber.php, src/Subscriber/TestRunner/ExecutionFinishedSubscriber.php
=> Fix: Rename subscribers

psalm-baseline.xml, test/EndToEnd/Version08/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version08/TestCase/Combination/test.phpt, test/EndToEnd/Version08/TestCase/WithDataProvider/SleeperTest.php, test/EndToEnd/Version08/TestCase/WithDataProvider/phpunit.xml, test/EndToEnd/Version08/TestCase/WithDataProvider/test.phpt, test/EndToEnd/Version09/TestCase/Combination/test.phpt, test/EndToEnd/Version09/TestCase/WithDataProvider/SleeperTest.php, test/EndToEnd/Version09/TestCase/WithDataProvider/phpunit.xml, test/EndToEnd/Version09/TestCase/WithDataProvider/test.phpt, test/EndToEnd/Version10/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version10/TestCase/Combination/test.phpt, test/EndToEnd/Version10/TestCase/WithDataProvider/SleeperTest.php, test/EndToEnd/Version10/TestCase/WithDataProvider/phpunit.xml, test/EndToEnd/Version10/TestCase/WithDataProvider/test.phpt, test/EndToEnd/Version11/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version11/TestCase/Combination/test.phpt, test/EndToEnd/Version11/TestCase/WithDataProvider/SleeperTest.php, test/EndToEnd/Version11/TestCase/WithDataProvider/phpunit.xml, test/EndToEnd/Version11/TestCase/WithDataProvider/test.phpt
=> Fix: Sleep in data provider

composer.json, composer.lock
=> Fix: Allow installation of unstable dependencies

.github/workflows/integrate.yaml, Makefile, test/Phar/Version10/SleeperTest.php, test/Phar/Version10/bootstrap.php, test/Phar/Version10/phpunit.xml
=> Fix: Move tests

README.md
=> Fix: Simplify `README.md`

.github/settings.yml, .github/workflows/integrate.yaml
=> Fix: Build Phar on PHP 7.4

.github/workflows/integrate.yaml
=> Fix: Slide step

.github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/release.yaml, .php-cs-fixer.php, CHANGELOG.md, composer.json, composer.lock, rector.php
=> Enhancement: Add support for PHP 7.1

psalm-baseline.xml, src/Exception/InvalidTestDescription.php, src/Extension.php, src/Reporter/DefaultReporter.php, src/SlowTest.php, src/Subscriber/Test/FinishedSubscriber.php, src/TestDescription.php, test/Unit/Collector/DefaultCollectorTest.php, test/Unit/Exception/InvalidTestDescriptionTest.php, test/Unit/Reporter/DefaultReporterTest.php, test/Unit/SlowTestTest.php, test/Unit/TestDescriptionTest.php
=> Enhancement: Implement `TestDescription`

.github/workflows/integrate.yaml
=> Fix: Adjust build matrix

phpstan-baseline.neon, src/Count.php, src/Exception/InvalidMaximumCount.php, src/Extension.php, src/MaximumCount.php, src/Reporter/DefaultReporter.php, test/Unit/CountTest.php, test/Unit/Exception/InvalidMaximumCountTest.php, test/Unit/MaximumCountTest.php, test/Unit/Reporter/DefaultReporterTest.php
=> Enhancement: Extract `MaximumCount`

README.md
to ease skimming the README for phpunit version specific parts
=> Readme: visually separate phpunit version specific paragraphs
