ergebnis/phpunit-slow-test-detector

Makefile
Follows #2.
💁‍♂️ Forgot to adjust `Makefile` in ed1d2c1.
=> Fix: Do not validate composer.json and composer.lock in strict mode

.php_cs
=> Enhancement: Use Php74 rule set

CHANGELOG.md, src/Subscriber/TestPreparedSubscriber.php, test/Unit/Subscriber/TestPreparedSubscriberTest.php
=> Enhancement: Implement TestPreparedSubscriber

CHANGELOG.md, src/Formatter/ToMillisecondsDurationFormatter.php, test/Unit/Formatter/ToMillisecondsDurationFormatterTest.php
=> Enhancement: Implement ToMillisecondsDurationFormatter

.php_cs, CHANGELOG.md, infection.json, phpstan.neon, src/Exception/MaximumNumberNotGreaterThanZero.php, src/SlowTestReporter.php, test/Fixture/ExampleTest.php, test/Unit/Exception/MaximumNumberNotGreaterThanZeroTest.php, test/Unit/SlowTestReporterTest.php
=> Enhancement: Implement SlowTestReporter

CHANGELOG.md, src/Collector.php, src/SlowTestCollector.php, test/Unit/CollectorTest.php, test/Unit/SlowTestCollectorTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php, test/Unit/Subscriber/TestPreparedSubscriberTest.php
=> Enhancement: Extract Collector

CHANGELOG.md, src/Collector/Collector.php, src/Collector/DefaultCollector.php, src/SlowTestCollector.php, test/Double/Collector/AppendingCollector.php, test/Unit/Collector/DefaultCollectorTest.php, test/Unit/SlowTestCollectorTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php, test/Unit/Subscriber/TestPreparedSubscriberTest.php
💁‍♂️ Useful for people who prefer to implement a different collector, for example
- averaging
- minimizing
The current - default - implementation picks the slowest test run for a given test when there are multiple test runs for the same tests. This usually happens when people run tests with the `--repeat` option, for example
```
$ vendor/bin/phpunit --repeat=100
```
=> Enhancement: Rename Collector to Collector\DefaultCollector and extract Collector\Collector interface

CHANGELOG.md, src/Subscriber/TestPreparedSubscriber.php, test/Unit/Subscriber/TestPreparedSubscriberTest.php
=> Enhancement: Use TimeKeeper instead of SlowTestCollector in Subscriber\TestPreparedSubscriber

CHANGELOG.md, src/Subscriber/TestPassedSubscriber.php, test/Unit/Subscriber/TestPassedSubscriberTest.php
=> Enhancement: Use TimeKeeper and Collector\Collector instead of SlowTestCollector in Subscriber\TestPassedSubscriber

test/Example/Sleeper.php, test/Example/SleeperTest.php
=> Fix: Move Sleeper

src/Reporter/DefaultReporter.php, test/Unit/Reporter/DefaultReporterTest.php
=> Fix: Avoid trailing new lines in report

src/Reporter/DefaultReporter.php, test/Unit/Reporter/DefaultReporterTest.php
=> Fix: Account for a single slow test in report

CHANGELOG.md, src/SlowTest.php, src/Subscriber/TestPassedSubscriber.php, test/Unit/Collector/DefaultCollectorTest.php, test/Unit/Reporter/DefaultReporterTest.php, test/Unit/SlowTestTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php, test/Unit/Subscriber/TestSuiteFinishedSubscriberTest.php
💁‍♂️ This makes sense when we start reading maximum durations from DocBlocks for tests - we can then use the specific maximum duration to render it in the report.
=> Enhancement: Compose maximum duration into SlowTest

CHANGELOG.md, src/Reporter/DefaultReporter.php, test/Unit/Reporter/DefaultReporterTest.php
=> Enhancement: Include maximum duration for each slow test in report

src/Console/Color.php, src/Reporter/DefaultReporter.php, test/Unit/Console/ColorTest.php, test/Unit/Reporter/DefaultReporterTest.php
=> Enhancement: Dim maximum duration in report output

src/TimeKeeper.php, test/Unit/Comparator/DurationComparatorTest.php, test/Unit/SlowTestTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php, test/Unit/Subscriber/TestPreparedSubscriberTest.php, test/Unit/Subscriber/TestSuiteFinishedSubscriberTest.php, test/Unit/TimeKeeperTest.php
=> Fix: Do not use named constructor

CHANGELOG.md, README.md, src/Exception/InvalidMaximumDuration.php, src/MaximumDuration.php, src/Reporter/DefaultReporter.php, src/Subscriber/TestPassedSubscriber.php, test/Example/bootstrap.php, test/Unit/Exception/InvalidMaximumDurationTest.php, test/Unit/MaximumDurationTest.php, test/Unit/Reporter/DefaultReporterTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php
💁‍♂️ It's perhaps a little bit more convenient to use.
=> Enhancement: Implement MaximumDuration

CHANGELOG.md, README.md, src/Exception/InvalidMaximumCount.php, src/MaximumCount.php, src/Reporter/DefaultReporter.php, test/Example/bootstrap.php, test/Unit/Exception/InvalidMaximumCountTest.php, test/Unit/MaximumCountTest.php, test/Unit/Reporter/DefaultReporterTest.php
=> Enhancement: Add MaximumCount

CHANGELOG.md, psalm-baseline.xml, src/Subscriber/TestPassedSubscriber.php, test/Example/SleeperTest.php, test/Unit/Subscriber/TestPassedSubscriberTest.php
💁‍♂️ See https://github.com/johnkary/phpunit-speedtrap/tree/v3.3.0#custom-slowness-threshold-per-test-case.
=> Enhancement: Allow configuring maximum duration with @slowThreshold annotation

test/Unit/Console/ColorTest.php, test/Unit/MaximumCountTest.php, test/Unit/MaximumDurationTest.php
=> Enhancement: Use data providers provided by `ergebnis/data-provider`

.php-cs-fixer.php, src/Reporter/DefaultReporter.php, src/SlowTest.php, src/Subscriber/TestPassedSubscriber.php
=> Enhancement: Use `Php80` rule set

psalm-baseline.xml, src/MaximumCount.php, src/MaximumDuration.php, src/Reporter/DefaultReporter.php, src/SlowTest.php, src/Subscriber/TestPassedSubscriber.php, src/Subscriber/TestPreparedSubscriber.php, src/Subscriber/TestSuiteFinishedSubscriber.php, test/Example/Sleeper.php
=> Enhancement: Make use of constructor property promotion

test/Unit/Console/ColorTest.php, test/Unit/MaximumCountTest.php, test/Unit/MaximumDurationTest.php
=> Fix: Remove parentheses

psalm-baseline.xml, test/Unit/Console/ColorTest.php, test/Unit/SlowTestTest.php, test/Unit/Subscriber/TestSuiteFinishedSubscriberTest.php
=> Fix: Use methods instead of deprecated magic properties

psalm-baseline.xml, src/Formatter/ToMillisecondsDurationFormatter.php
=> Fix: Mark object as immutabke

composer.json
=> Fix: Allow `composer` plugins

CHANGELOG.md, src/Extension.php, test/EndToEnd/MaximumDuration/Default/phpunit.xml, test/EndToEnd/MaximumDuration/Default/test.phpt, test/EndToEnd/MaximumDuration/Fifty/phpunit.xml, test/EndToEnd/MaximumDuration/Fifty/test.phpt
=> Enhancement: Allow configuring the maximum duration via `maximum-duration` parameter

README.md
=> Fix: Add documentation for `maximum-duration` parameter

CHANGELOG.md, src/Collector/Collector.php, src/Collector/DefaultCollector.php, src/Comparator/DurationComparator.php, src/Console/Color.php, src/Exception/InvalidMaximumCount.php, src/Exception/InvalidMaximumDuration.php, src/Formatter/DurationFormatter.php, src/Formatter/ToMillisecondsDurationFormatter.php, src/MaximumCount.php, src/MaximumDuration.php, src/Reporter/DefaultReporter.php, src/Reporter/Reporter.php, src/SlowTest.php, src/Subscriber/TestPassedSubscriber.php, src/Subscriber/TestPreparedSubscriber.php, src/Subscriber/TestRunnerExecutionFinishedSubscriber.php, src/TimeKeeper.php
=> Fix: Mark classes and interfaces as internal

CHANGELOG.md, src/Subscriber/TestPassedSubscriber.php, test/EndToEnd/MaximumDuration/Fifty/test.phpt
=> Fix: Resolve maximum duration from `@slowThreshold` annotation

CHANGELOG.md, README.md, src/Reporter/DefaultReporter.php, test/EndToEnd/Default/test.phpt, test/EndToEnd/MaximumCount/Five/test.phpt, test/EndToEnd/MaximumDuration/Fifty/test.phpt
=> Enhancement: Render slow tests as ordered list

CHANGELOG.md, src/Extension.php, test/EndToEnd/NoOutput/SleeperTest.php, test/EndToEnd/NoOutput/phpunit.xml, test/EndToEnd/NoOutput/test.phpt
=> Fix: Do not register extension when running `phpunit` with the `--no-output` option

.github/workflows/release.yaml, CHANGELOG.md
=> Fix: Prevent inclusion of `phpunit/phpunit` in PHAR

CHANGELOG.md, src/Formatter/DefaultDurationFormatter.php
=> Fix: Mark `DefaultDurationFormatter` as internal

CHANGELOG.md, psalm-baseline.xml, src/Comparator/DurationComparator.php, src/Duration.php, src/Exception/InvalidNanoseconds.php, src/Exception/InvalidSeconds.php, src/Formatter/DefaultDurationFormatter.php, src/Formatter/DurationFormatter.php, src/MaximumDuration.php, src/Reporter/DefaultReporter.php, src/SlowTest.php, src/Subscriber/TestPassedSubscriber.php, src/TimeKeeper.php, test/Unit/Comparator/DurationComparatorTest.php, test/Unit/DurationTest.php, test/Unit/Exception/InvalidNanosecondsTest.php, test/Unit/Exception/InvalidSecondsTest.php, test/Unit/Formatter/DefaultDurationFormatterTest.php, test/Unit/MaximumDurationTest.php
=> Enhancement: Extract `Duration`

CHANGELOG.md, src/Count.php, src/Exception/InvalidCount.php, src/Extension.php, src/Reporter/DefaultReporter.php, test/Unit/CountTest.php, test/Unit/Exception/InvalidCountTest.php
=> Fix: Rename `MaximumCount` to `Count`

CHANGELOG.md, psalm-baseline.xml, src/Exception/InvalidStart.php, src/Subscriber/TestPassedSubscriber.php, src/Subscriber/TestPreparedSubscriber.php, src/Time.php, src/TimeKeeper.php, test/Unit/Exception/InvalidStartTest.php, test/Unit/TimeTest.php
=> Enhancement: Extract `Time`

CHANGELOG.md, psalm-baseline.xml, src/Collector/DefaultCollector.php, src/Exception/InvalidTestIdentifier.php, src/Reporter/DefaultReporter.php, src/SlowTest.php, src/Subscriber/TestPassedSubscriber.php, src/Subscriber/TestPreparedSubscriber.php, src/TestIdentifier.php, src/TimeKeeper.php, test/Unit/Exception/InvalidTestIdentifierTest.php, test/Unit/SlowTestTest.php, test/Unit/TestIdentifierTest.php, test/Unit/TimeKeeperTest.php
=> Enhancement: Extract `TestIdentifier`

.github/settings.yml, .github/workflows/integrate.yaml, Makefile, psalm-baseline.xml, src/Reporter/DefaultReporter.php, test/Unit/Attribute/MaximumDurationTest.php, test/Unit/Collector/DefaultCollectorTest.php, test/Unit/Comparator/DurationComparatorTest.php, test/Unit/Console/ColorTest.php, test/Unit/CountTest.php, test/Unit/DurationTest.php, test/Unit/Exception/InvalidCountTest.php, test/Unit/Exception/InvalidMillisecondsTest.php, test/Unit/Exception/InvalidNanosecondsTest.php, test/Unit/Exception/InvalidSecondsTest.php, test/Unit/Exception/InvalidStartTest.php, test/Unit/Exception/InvalidTestIdentifierTest.php, test/Unit/Formatter/DefaultDurationFormatterTest.php, test/Unit/Reporter/DefaultReporterTest.php, test/Unit/SlowTestTest.php, test/Unit/TestIdentifierTest.php, test/Unit/TimeKeeperTest.php, test/Unit/TimeTest.php, test/Unit/phpunit.xml
=> Enhancement: Run unit tests with phpunit/phpunit:^9.6.0

test/EndToEnd/Version10/CustomConfiguration/SleeperTest.php, test/EndToEnd/Version10/CustomConfiguration/phpunit.xml, test/EndToEnd/Version10/CustomConfiguration/test.phpt, test/EndToEnd/Version10/DefaultConfiguration/SleeperTest.php, test/EndToEnd/Version10/DefaultConfiguration/test.phpt, test/EndToEnd/Version8/CustomConfiguration/SleeperTest.php, test/EndToEnd/Version8/CustomConfiguration/phpunit.xml, test/EndToEnd/Version8/CustomConfiguration/test.phpt, test/EndToEnd/Version8/DefaultConfiguration/SleeperTest.php, test/EndToEnd/Version8/DefaultConfiguration/test.phpt, test/EndToEnd/Version9/CustomConfiguration/SleeperTest.php, test/EndToEnd/Version9/CustomConfiguration/phpunit.xml, test/EndToEnd/Version9/CustomConfiguration/test.phpt, test/EndToEnd/Version9/DefaultConfiguration/SleeperTest.php, test/EndToEnd/Version9/DefaultConfiguration/test.phpt
=> Fix: Clean up tests

test/EndToEnd/Version10/DefaultConfiguration/SleeperTest.php, test/EndToEnd/Version8/DefaultConfiguration/SleeperTest.php, test/EndToEnd/Version9/DefaultConfiguration/SleeperTest.php
=> Fix: Sleep longer during `setUpBeforeClass()` and `tearDownAfterClass()`

.github/workflows/integrate.yaml
=> Fix: Run unit tests with `phpunit/phpunit:^8.5.19`

README.md
=> Fix: Adjust documentation

test/EndToEnd/Version10/DefaultConfiguration/SleeperTest.php, test/EndToEnd/Version10/DefaultConfiguration/test.phpt, test/EndToEnd/Version8/DefaultConfiguration/SleeperTest.php, test/EndToEnd/Version8/DefaultConfiguration/test.phpt, test/EndToEnd/Version9/DefaultConfiguration/SleeperTest.php, test/EndToEnd/Version9/DefaultConfiguration/test.phpt
extracted from #380
runInSeparateProcess is executed very differently, so test it, fixes will be done in #380
=> Add tests for scenarios where tests are running in separate processes

src/Exception/InvalidPhaseIdentifier.php, src/Phase.php, src/PhaseIdentifier.php, src/PhaseStart.php, src/Subscriber/TestPassedSubscriber.php, src/Subscriber/TestPreparedSubscriber.php, src/TimeKeeper.php, test/Unit/Exception/InvalidPhaseIdentifierTest.php, test/Unit/PhaseIdentifierTest.php, test/Unit/PhaseStartTest.php, test/Unit/PhaseTest.php, test/Unit/TimeKeeperTest.php
=> Enhancement: Implement `PhaseStart` and `Phase`

src/Exception/PhaseNotStarted.php, src/TimeKeeper.php, test/Unit/Exception/PhaseNotStartedTest.php, test/Unit/TimeKeeperTest.php
=> Fix: Throw `PhaseNotStarted` exception when phase was not started

.github/workflows/integrate.yaml
=> Fix: Run appropriate tests with `phpunit/phpunit:11.0.x-dev`

psalm-baseline.xml, test/EndToEnd/Version10/TestCase/WithAssertPreConditions/SleeperTest.php, test/EndToEnd/Version10/TestCase/WithAssertPreConditions/phpunit.xml, test/EndToEnd/Version10/TestCase/WithAssertPreConditions/test.phpt, test/EndToEnd/Version11/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version11/TestCase/WithAssertPreConditions/SleeperTest.php, test/EndToEnd/Version11/TestCase/WithAssertPreConditions/phpunit.xml, test/EndToEnd/Version11/TestCase/WithAssertPreConditions/test.phpt, test/EndToEnd/Version8/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version8/TestCase/Combination/test.phpt, test/EndToEnd/Version8/TestCase/WithAssertPreConditions/SleeperTest.php, test/EndToEnd/Version8/TestCase/WithAssertPreConditions/phpunit.xml, test/EndToEnd/Version8/TestCase/WithAssertPreConditions/test.phpt, test/EndToEnd/Version8/TestMethod/WithRunInSeparateProcessAnnotation/SleeperTest.php, test/EndToEnd/Version8/TestMethod/WithRunInSeparateProcessAnnotation/test.phpt, test/EndToEnd/Version9/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version9/TestCase/Combination/test.phpt, test/EndToEnd/Version9/TestCase/WithAssertPreConditions/SleeperTest.php, test/EndToEnd/Version9/TestCase/WithAssertPreConditions/phpunit.xml, test/EndToEnd/Version9/TestCase/WithAssertPreConditions/test.phpt, test/EndToEnd/Version9/TestMethod/WithRunInSeparateProcessAnnotation/SleeperTest.php, test/EndToEnd/Version9/TestMethod/WithRunInSeparateProcessAnnotation/test.phpt
=> Fix: Sleep in `assertPreConditions()`

psalm-baseline.xml, test/EndToEnd/Version08/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version08/TestCase/Combination/test.phpt, test/EndToEnd/Version08/TestCase/WithAfterAnnotation/SleeperTest.php, test/EndToEnd/Version08/TestCase/WithAfterAnnotation/phpunit.xml, test/EndToEnd/Version08/TestCase/WithAfterAnnotation/test.phpt, test/EndToEnd/Version08/TestMethod/WithRunInSeparateProcessAnnotation/SleeperTest.php, test/EndToEnd/Version08/TestMethod/WithRunInSeparateProcessAnnotation/test.phpt, test/EndToEnd/Version09/TestCase/WithAfterAnnotation/SleeperTest.php, test/EndToEnd/Version09/TestCase/WithAfterAnnotation/phpunit.xml, test/EndToEnd/Version09/TestCase/WithAfterAnnotation/test.phpt, test/EndToEnd/Version09/TestMethod/WithRunInSeparateProcessAnnotation/SleeperTest.php, test/EndToEnd/Version09/TestMethod/WithRunInSeparateProcessAnnotation/test.phpt, test/EndToEnd/Version10/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version10/TestCase/WithAfterAnnotation/SleeperTest.php, test/EndToEnd/Version10/TestCase/WithAfterAnnotation/phpunit.xml, test/EndToEnd/Version10/TestCase/WithAfterAnnotation/test.phpt, test/EndToEnd/Version10/TestCase/WithAfterAttribute/SleeperTest.php, test/EndToEnd/Version10/TestCase/WithAfterAttribute/phpunit.xml, test/EndToEnd/Version10/TestCase/WithAfterAttribute/test.phpt, test/EndToEnd/Version10/TestMethod/WithRunInSeparateProcessAnnotation/SleeperTest.php, test/EndToEnd/Version10/TestMethod/WithRunInSeparateProcessAttribute/SleeperTest.php, test/EndToEnd/Version11/TestCase/WithAfterAttribute/SleeperTest.php, test/EndToEnd/Version11/TestCase/WithAfterAttribute/phpunit.xml, test/EndToEnd/Version11/TestCase/WithAfterAttribute/test.phpt, test/EndToEnd/Version11/TestMethod/WithRunInSeparateProcessAttribute/SleeperTest.php
=> Fix: Sleep in method with `@after` annotation or `After` attribute

psalm-baseline.xml, test/EndToEnd/Version08/TestCase/Combination/test.phpt, test/EndToEnd/Version08/TestCase/WithBeforeAnnotation/SleeperTest.php, test/EndToEnd/Version08/TestCase/WithBeforeAnnotation/phpunit.xml, test/EndToEnd/Version08/TestCase/WithBeforeAnnotation/test.phpt, test/EndToEnd/Version08/TestMethod/WithRunInSeparateProcessAnnotation/SleeperTest.php, test/EndToEnd/Version08/TestMethod/WithRunInSeparateProcessAnnotation/test.phpt, test/EndToEnd/Version09/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version09/TestCase/Combination/test.phpt, test/EndToEnd/Version09/TestCase/WithBeforeAnnotation/SleeperTest.php, test/EndToEnd/Version09/TestCase/WithBeforeAnnotation/phpunit.xml, test/EndToEnd/Version09/TestCase/WithBeforeAnnotation/test.phpt, test/EndToEnd/Version09/TestMethod/WithRunInSeparateProcessAnnotation/SleeperTest.php, test/EndToEnd/Version09/TestMethod/WithRunInSeparateProcessAnnotation/test.phpt, test/EndToEnd/Version10/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version10/TestCase/WithBeforeAnnotation/SleeperTest.php, test/EndToEnd/Version10/TestCase/WithBeforeAnnotation/phpunit.xml, test/EndToEnd/Version10/TestCase/WithBeforeAnnotation/test.phpt, test/EndToEnd/Version10/TestCase/WithBeforeAttribute/SleeperTest.php, test/EndToEnd/Version10/TestCase/WithBeforeAttribute/phpunit.xml, test/EndToEnd/Version10/TestCase/WithBeforeAttribute/test.phpt, test/EndToEnd/Version10/TestMethod/WithRunInSeparateProcessAnnotation/SleeperTest.php, test/EndToEnd/Version10/TestMethod/WithRunInSeparateProcessAttribute/SleeperTest.php, test/EndToEnd/Version11/TestCase/WithBeforeAttribute/SleeperTest.php, test/EndToEnd/Version11/TestCase/WithBeforeAttribute/phpunit.xml, test/EndToEnd/Version11/TestCase/WithBeforeAttribute/test.phpt
=> Fix: Sleep in method with `@before` annotation or `Before` attribute

psalm-baseline.xml, test/EndToEnd/Version08/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version08/TestCase/WithBeforeClassAnnotation/SleeperTest.php, test/EndToEnd/Version08/TestCase/WithBeforeClassAnnotation/phpunit.xml, test/EndToEnd/Version08/TestCase/WithBeforeClassAnnotation/test.phpt, test/EndToEnd/Version08/TestMethod/WithRunInSeparateProcessAnnotation/SleeperTest.php, test/EndToEnd/Version08/TestMethod/WithRunInSeparateProcessAnnotation/test.phpt, test/EndToEnd/Version09/TestCase/WithBeforeClassAnnotation/SleeperTest.php, test/EndToEnd/Version09/TestCase/WithBeforeClassAnnotation/phpunit.xml, test/EndToEnd/Version09/TestCase/WithBeforeClassAnnotation/test.phpt, test/EndToEnd/Version09/TestMethod/WithRunInSeparateProcessAnnotation/SleeperTest.php, test/EndToEnd/Version09/TestMethod/WithRunInSeparateProcessAnnotation/test.phpt, test/EndToEnd/Version10/TestCase/Combination/SleeperTest.php, test/EndToEnd/Version10/TestCase/WithBeforeClassAnnotation/SleeperTest.php, test/EndToEnd/Version10/TestCase/WithBeforeClassAnnotation/phpunit.xml, test/EndToEnd/Version10/TestCase/WithBeforeClassAnnotation/test.phpt, test/EndToEnd/Version10/TestCase/WithBeforeClassAttribute/SleeperTest.php, test/EndToEnd/Version10/TestCase/WithBeforeClassAttribute/phpunit.xml, test/EndToEnd/Version10/TestCase/WithBeforeClassAttribute/test.phpt, test/EndToEnd/Version10/TestMethod/WithRunInSeparateProcessAnnotation/SleeperTest.php, test/EndToEnd/Version10/TestMethod/WithRunInSeparateProcessAttribute/SleeperTest.php, test/EndToEnd/Version11/TestCase/WithBeforeClassAttribute/SleeperTest.php, test/EndToEnd/Version11/TestCase/WithBeforeClassAttribute/phpunit.xml, test/EndToEnd/Version11/TestCase/WithBeforeClassAttribute/test.phpt, test/EndToEnd/Version11/TestMethod/WithRunInSeparateProcessAttribute/SleeperTest.php
=> Fix: Sleep in method with `@beforeClass` annotation or `BeforeClass` attribute

.github/dependabot.yaml, .github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/renew.yaml, Makefile
=> Enhancement: Synchronize with `ergebnis/php-package-template`

.github/workflows/integrate.yaml, .github/workflows/release.yaml, .gitignore, .phive/phars.xml, Makefile, test/Phar/Version10/composer.json, test/Phar/Version10/composer.lock, test/Phar/Version10/phpunit.xml
=> Enhancement: Install `phpunit/phpunit` for Phar tests with `composer`

.github/workflows/integrate.yaml
=> Enhancement: Split compiling and testing Phar

test/Phar/Version10/phpunit.xml, test/Phar/Version11/phpunit.xml
=> Fix: Remove deprecated `beStrictAboutTodoAnnotatedTests` option for tests running on `phpunit/phpunit:^10.0.0` and `phpunit/phpunit:^11.0.0`

.gitattributes, .github/workflows/integrate.yaml, CHANGELOG.md, bin/remove-autoload-configuration.php, box.json
=> Fix: Explicitly include `src/` directory when compiling PHAR

box.json
=> Fix: Link to schema

.github/workflows/integrate.yaml
=> Fix: Run end-to-end and phar tests with `phpunit/phpunit:8.5.40`

phpstan-baseline.neon, src/Collector/DefaultCollector.php, src/Extension.php, src/MaximumDuration.php, src/Reporter/DefaultReporter.php, src/SlowTest.php, src/Subscriber/Test/FinishedSubscriber.php, src/TestDuration.php, test/Unit/Collector/DefaultCollectorTest.php, test/Unit/MaximumDurationTest.php, test/Unit/Reporter/DefaultReporterTest.php, test/Unit/SlowTestTest.php, test/Unit/TestDurationTest.php
=> Enhancement: Extract `TestDuration` and `MaximumDuration`

phpstan-baseline.neon, src/Collector/Collector.php, src/Collector/DefaultCollector.php, src/Count.php, src/Exception/SlowTestListIsEmpty.php, src/Extension.php, src/Reporter/DefaultReporter.php, src/SlowTestCount.php, src/SlowTestList.php, src/Subscriber/TestRunner/ExecutionFinishedSubscriber.php, test/Unit/Collector/DefaultCollectorTest.php, test/Unit/CountTest.php, test/Unit/Exception/SlowTestListIsEmptyTest.php, test/Unit/Reporter/DefaultReporterTest.php, test/Unit/SlowTestCountTest.php, test/Unit/SlowTestListTest.php
=> Enhancement: Extract `SlowTestList`
